Some fixes to make things work with either wslpath or cygpath. Added coloration for shortcut keys in nano's help text. Reorganized some of my prompt setup. Minor updates to setup_base_env and bash_functions. Added aliases to make a few commands safer. Added assorted file generators

diff --git a/windowsOnly/bin/explorer b/windowsOnly/bin/explorer
--- a/windowsOnly/bin/explorer
+++ b/windowsOnly/bin/explorer
@@ -1,21 +1,69 @@
 #!/bin/bash
 #-xv
 
+# Realistically, this script will take precedence over an executable with the same name situated on the system path, but will be superseded by an alias or function. As such, it is fairly safe to assume that when this script tries to run "explorer", it is trying to run the file "explorer.exe", located in $SYSTEMROOT, where $SYSTEMROOT is typically "C:\Windows"(/c/Windows)
+# While there ARE a handful of documented (and probably many more undocumented) command line switches for explorer.exe, most of them likely wont be used, so this script lacks any special handling for them. 
+# NOTE: This has worked surprisingly well with unix-style paths so far, but it hasn't seen much use from WSL, so it may yet require some modifications for compatability that msys or mintty already has builtin.
+
+
+
+# # Recycle bin can be opened with `explorer.exe "shell:RecycleBinFolder"` or `start "" "shell:RecycleBinFolder"`
+
 if [[ $# == 0 ]]; then
-	explorer.exe .
+	$SYSTEMROOT/explorer.exe .
 	exit 0
 fi
 
-if [ ! -e "$1" ]; then
-	echo "\"$1\" does not exist"
-	exit 1
-fi
+# {
+# if [ ! -e "$1" ]; then
+	# echo "\"$1\" does not exist"
+	# exit 1
+# fi
 
-pushd "$1" >/dev/null 2>&1
-explorer.exe . >/dev/null 2>&1
-popd >/dev/null 2>&1
+# pushd "$1" >/dev/null 2>&1	# ignore any errors, such as paths that dont exist
+# $SYSTEMROOT/explorer.exe . >/dev/null 2>&1
+# popd >/dev/null 2>&1
 
-# pushd $1
-# explorer.exe .
-# popd
-exit 0
+# # pushd $1
+# # $SYSTEMROOT/explorer.exe .
+# # popd
+# exit 0
+# }
+
+# Partially viable; does not work with paths containing spaces
+# function goto(){
+	# if [ ! -d "$1" ]; then
+		# echo "\"$1\" does not exist"
+		# return 1
+	# fi
+	# $SYSTEMROOT/explorer.exe "$1" >/dev/null 2>&1
+	# return 0
+# }
+
+## Viable, but utilizes a local variable
+# function goto(){
+	# pushd "$1" >/dev/null 2>&1 || local rv=1
+	# if [ ! -v rv ]; then
+		# $SYSTEMROOT/explorer.exe . >/dev/null 2>&1
+		# popd >/dev/null 2>&1
+		# return 0
+	# fi
+	# return 1
+# }
+	
+# Not viable; returns 1 for everything
+# function goto(){
+	# [[ -d "$1" ]] && ($SYSTEMROOT/explorer.exe "$1" && return 0) || return 1
+# }	
+
+# Not ideal that it uses the directory stack, but otherwise no issues with this one
+function goto(){
+	pushd "$1" >/dev/null 2>&1 || return 1	
+	$SYSTEMROOT/explorer.exe . >/dev/null 2>&1
+	popd >/dev/null 2>&1
+	return 0	
+}
+
+for loc in "$@"; do
+	goto "$loc" || echo 'explorer: "'"$loc"'":No such directory. Ignoring invalid path.'
+done
diff --git a/windowsOnly/bin/wpv b/windowsOnly/bin/wpv
--- a/windowsOnly/bin/wpv
+++ b/windowsOnly/bin/wpv
@@ -3,12 +3,16 @@
 limit=10	# Maximum number of files to open at once. Can be overriden with --limit
 
 function usage(){
-	printf "Usage: wpv [--help | -h | --limit NUM] FILEPATHS...\n"
-	printf "    Attempt to open up to $limit FILEPATHS in Windows Photo Viewer.\n"
-	printf "    This limit can be overriden using the --limit option.\n\n"
-	printf "    Options:\n"
-	printf "      -h, --help        Display this help and exit.\n"
-	printf "          --limit NUM   Override the default limit of $limit files with NUM.\n"
+cat << EOF
+Usage: wpv [--help | -h | --limit NUM] FILEPATHS...
+    Attempt to open up to $limit FILEPATHS in Windows Photo Viewer.
+    This limit can be overriden using the --limit option.
+	
+    Options:
+      -h, --help        Display this help and exit.
+          --limit NUM   Override the default limit of files which can be opened at once with NUM (Default limit is $limit).
+                        Note that specifying a value less than 1 will remove the limit.
+EOF
 }
 
 if [[ $# == 0 ]]; then
@@ -33,13 +37,28 @@ function view(){
 	rundll32 "C:\Program Files\Windows Photo Viewer\PhotoViewer.dll" ImageView_Fullscreen $1 &
 	# disown
 }
+# if [ -n $(type -t cygpath) ]; then
+	# echo path is "$(cygpath --windows -a "$1")"
+	# view "$(cygpath --windows -a "$1")"
+# fi
+# elif [ -n $(type -t wslpath) ]; then
+	# echo path is "$(wslpath -wa "$1")"
+	# view "$(wslpath -wa "$1")"
+# fi
 
-#echo path is "$(cygpath --windows -a "$1")"
-# view "$(cygpath --windows -a "$1")"
+if [ -n $(type -t cygpath) ]; then
+	winPath="$(cygpath --windows -a "$@")"
+elif [ -n $(type -t wslpath) ]; then
+	winPath="$(wslpath -wa "$@")"
+else
+	echo "Neither cygpath nor wslpath found. No known alternative for ensuring Windows-style file paths. Aborting..."
+	exit 1
+fi
 
-winPath="$(cygpath --windows -a "$@")"
+
 # echo -e "\033[34m$winPath\033[0m"
 
+# By default, there is a limit to how many files can be opened by running this script once. This is to prevent a user from accidentally opening tens of files at once using globbing.
 i=0
 while read -r foo; do
 	# echo -e "\033[1;34m$foo\033[0m"
